export const API_BASE_URL = "http://localhost:3001/api/v1";

export const API_ENDPOINTS_FROM_NEXT = {
  CATEGORIES: "/api/home/categories",
  BLOGS_HOME: "/api/home/blogs",
  PRODUCTS_BEST_SELLING: "/api/home/products/best-selling",
  PRODUCTS_IS_FEATURED: "/api/home/products/is-featured",
  PRODUCTS_SLIDER: "/api/home/products/slider",
  PRODUCTS_IS_NEW: "/api/home/products/is-new",
  SHOP: "/api/shop",
  BLOGS: "/api/blogs",
  BLOG_FILTERS: "/api/blog-filters",
  BLOG_FILTER: "/api/blog/filter",
  ADDRESSES: "/api/addresses/addresses",
  ADDRESS_UPDATE: "/api/addresses/address-update",
  ADDRESS_CREATE: "/api/addresses/address-create",
  ADDRESS_DELETE: "/api/addresses/address-delete",
  ADDRESS_SET_DEFAULT: "/api/address/set-default-address",
  ADDRESS_SHIPMENT: "/api/addresses",
  USER_UPDATE: "/user/update",
  REFRESH_TOKENS: "/api/auth/refresh-tokens",
  QUIZ_QUESTIONS: "/api/quiz/questions-with-answers",
  MEGA_MENU_CATEGORIES: "/api/mega-menu/categories",
  MEGA_MENU_BLOG_CATEGORIES: "/api/mega-menu/blog-categories",
  COUPON_VALIDATE: "/api/coupon/validate",
  SHAPES_GROUPED: "/api/shapes/grouped",
  SHAPES_PARTS: "/api/shapes/parts",
  BOOKS_FINDER: "/api/books/finder",
  BOOKS_PAGES: "/api/books/pages",
};

export const API_ENDPOINTS_FROM_SERVER = {
  CATEGORIES: `/category/front`,
  SUB_CATEGORIES: `/sub-category/front`,
  PRODUCTS: `/product/front`,
  BLOGS: `/blog/front`,
  GENERAL_SETTINGS: `/general-settings/index`,
  MEGA_MENU_CATEGORIES: `/category/product`,
  MEGA_MENU_BLOG_CATEGORIES: `/category/blog`,
  PAYMENT_METHODS: `/payment-methods/front`,
  BANKS: `/bank/front`,
  QUIZ_QUESTIONS: `/quiz/questions-with-answers`,
  COUPON_VALIDATE: `/coupon/validate`,
  SHAPES_GROUPED: `/shapes/grouped`,
  SHAPES_PARTS: `/shapes/parts`,
  BOOKS_FINDER: `/books/finder`,
  BOOKE_PAGES: "/books/pages",
};

export const API_ENDPOINTS_FROM_SERVER_DASHBOARD = {
  ADDRESSES: `/api/addresses/addresses`,
  ADDRESS_UPDATE: `/address/update`,
  ADDRESS_CREATE: `/address/store`,
  ADDRESS_DELETE: `/address/delete`,
  ADDRESS_SET_DEFAULT: `/address/set-default`,
};
